version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: taskmanager_db
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: taskmanager_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend/TaskManager.API
      dockerfile: Dockerfile
    container_name: taskmanager_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=taskmanager;Username=postgres;Password=postgres123
      - Jwt__Key=TaskManager_SuperSecret_Key_MinLength32_2025!
      - Jwt__Issuer=TaskManagerAPI
      - Jwt__Audience=TaskManagerClient
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskmanager_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: