// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManager.API.Data;

#nullable disable

namespace TaskManager.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManager.API.Models.AuditLog", b =>
            {
                b.Property<int>("LogId").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("log_id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));
                b.Property<string>("ActionType").IsRequired().HasColumnType("text").HasColumnName("action_type");
                b.Property<string>("Details").HasColumnType("text").HasColumnName("details");
                b.Property<string>("IpAddress").HasColumnType("text").HasColumnName("ip_address");
                b.Property<string>("ObjectType").IsRequired().HasColumnType("text").HasColumnName("object_type");
                b.Property<int?>("ObjectId").HasColumnType("integer").HasColumnName("object_id");
                b.Property<DateTime>("Timestamp").HasColumnType("timestamp with time zone").HasColumnName("timestamp");
                b.Property<int?>("UserId").HasColumnType("integer").HasColumnName("user_id");
                b.HasKey("LogId");
                b.HasIndex("UserId");
                b.ToTable("audit_log");
            });

            modelBuilder.Entity("TaskManager.API.Models.Comment", b =>
            {
                b.Property<int>("CommentId").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("comment_id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));
                b.Property<int>("AuthorId").HasColumnType("integer").HasColumnName("author_id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<string>("Text").IsRequired().HasColumnType("text").HasColumnName("text");
                b.Property<int>("TaskId").HasColumnType("integer").HasColumnName("task_id");
                b.HasKey("CommentId");
                b.HasIndex("AuthorId");
                b.HasIndex("TaskId");
                b.ToTable("comments");
            });

            modelBuilder.Entity("TaskManager.API.Models.Department", b =>
            {
                b.Property<int>("DepartmentId").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("department_id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));
                b.Property<string>("DepartmentName").IsRequired().HasColumnType("text").HasColumnName("department_name");
                b.Property<int?>("ParentDepartmentId").HasColumnType("integer").HasColumnName("parent_department_id");
                b.HasKey("DepartmentId");
                b.HasIndex("ParentDepartmentId");
                b.ToTable("departments");
            });

            modelBuilder.Entity("TaskManager.API.Models.Event", b =>
            {
                b.Property<int>("EventId").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("event_id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));
                b.Property<DateTime>("EndDatetime").HasColumnType("timestamp with time zone").HasColumnName("end_datetime");
                b.Property<string>("EventType").IsRequired().HasDefaultValue("meeting").HasColumnType("text").HasColumnName("event_type");
                b.Property<DateTime>("StartDatetime").HasColumnType("timestamp with time zone").HasColumnName("start_datetime");
                b.Property<string>("Title").IsRequired().HasColumnType("text").HasColumnName("title");
                b.Property<int>("UserId").HasColumnType("integer").HasColumnName("user_id");
                b.HasKey("EventId");
                b.HasIndex("UserId");
                b.ToTable("events");
            });

            modelBuilder.Entity("TaskManager.API.Models.Report", b =>
            {
                b.Property<int>("ReportId").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("report_id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));
                b.Property<DateTime>("GeneratedAt").HasColumnType("timestamp with time zone").HasColumnName("generated_at");
                b.Property<int>("GeneratedBy").HasColumnType("integer").HasColumnName("generated_by");
                b.Property<DateTime>("PeriodEnd").HasColumnType("timestamp with time zone").HasColumnName("period_end");
                b.Property<DateTime>("PeriodStart").HasColumnType("timestamp with time zone").HasColumnName("period_start");
                b.Property<string>("ReportType").IsRequired().HasColumnType("text").HasColumnName("report_type");
                b.HasKey("ReportId");
                b.HasIndex("GeneratedBy");
                b.ToTable("reports");
            });

            modelBuilder.Entity("TaskManager.API.Models.Role", b =>
            {
                b.Property<int>("RoleId").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("role_id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));
                b.Property<string>("Description").HasColumnType("text").HasColumnName("description");
                b.Property<string>("RoleName").IsRequired().HasColumnType("text").HasColumnName("role_name");
                b.HasKey("RoleId");
                b.ToTable("roles");
            });

            modelBuilder.Entity("TaskManager.API.Models.Status", b =>
            {
                b.Property<int>("StatusId").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("status_id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));
                b.Property<string>("StatusName").IsRequired().HasColumnType("text").HasColumnName("status_name");
                b.HasKey("StatusId");
                b.ToTable("statuses");
            });

            modelBuilder.Entity("TaskManager.API.Models.TaskHistory", b =>
            {
                b.Property<int>("HistoryId").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("history_id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));
                b.Property<int>("ChangedBy").HasColumnType("integer").HasColumnName("changed_by");
                b.Property<DateTime>("ChangedAt").HasColumnType("timestamp with time zone").HasColumnName("changed_at");
                b.Property<string>("Comment").HasColumnType("text").HasColumnName("comment");
                b.Property<int?>("NewStatusId").HasColumnType("integer").HasColumnName("new_status");
                b.Property<int?>("OldStatusId").HasColumnType("integer").HasColumnName("old_status");
                b.Property<int>("TaskId").HasColumnType("integer").HasColumnName("task_id");
                b.HasKey("HistoryId");
                b.HasIndex("ChangedBy");
                b.HasIndex("NewStatusId");
                b.HasIndex("OldStatusId");
                b.HasIndex("TaskId");
                b.ToTable("task_history");
            });

            modelBuilder.Entity("TaskManager.API.Models.TaskItem", b =>
            {
                b.Property<int>("TaskId").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("task_id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskId"));
                b.Property<DateTime?>("CompletedAt").HasColumnType("timestamp with time zone").HasColumnName("completed_at");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<int>("CreatorId").HasColumnType("integer").HasColumnName("creator_id");
                b.Property<string>("Description").IsRequired().HasColumnType("text").HasColumnName("description");
                b.Property<DateTime>("DueDate").HasColumnType("timestamp with time zone").HasColumnName("due_date");
                b.Property<int?>("ExecutorId").HasColumnType("integer").HasColumnName("executor_id");
                b.Property<string>("Priority").IsRequired().HasDefaultValue("medium").HasColumnType("text").HasColumnName("priority");
                b.Property<int>("StatusId").HasColumnType("integer").HasColumnName("status_id");
                b.Property<string>("Title").IsRequired().HasColumnType("text").HasColumnName("title");
                b.HasKey("TaskId");
                b.HasIndex("CreatorId");
                b.HasIndex("ExecutorId");
                b.HasIndex("StatusId");
                b.ToTable("tasks");
            });

            modelBuilder.Entity("TaskManager.API.Models.User", b =>
            {
                b.Property<int>("UserId").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("user_id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<int?>("DepartmentId").HasColumnType("integer").HasColumnName("department_id");
                b.Property<string>("Email").IsRequired().HasColumnType("text").HasColumnName("email");
                b.Property<string>("FullName").IsRequired().HasColumnType("text").HasColumnName("full_name");
                b.Property<string>("Login").IsRequired().HasColumnType("text").HasColumnName("login");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text").HasColumnName("password_hash");
                b.Property<string>("Phone").HasColumnType("text").HasColumnName("phone");
                b.Property<string>("Position").HasColumnType("text").HasColumnName("position");
                b.Property<int>("RoleId").HasColumnType("integer").HasColumnName("role_id");
                b.Property<string>("Status").IsRequired().HasDefaultValue("active").HasColumnType("text").HasColumnName("status");
                b.HasKey("UserId");
                b.HasIndex("DepartmentId");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("Login").IsUnique();
                b.HasIndex("RoleId");
                b.ToTable("users");
            });
#pragma warning restore 612, 618
        }
    }
}
